# Default config
service:
  name: api-todo
  description:
  baseUrl: api/todo
  docsBaseUrl: docs/todo
  apiVersion: 0.1.0
  appVersion: 0.1.0

server:
  host: 127.0.0.1
  port: 3007
  hostname: 127.0.0.1:3007
  swaggerSchema: http

typeorm:
  type: postgres
  host: localhost
  username: postgres
  password: password
  port: 5434
  database: todo
  entities: []
  synchronize: true
  autoLoadEntities: true
  logging: false
